version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: n3_mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password_123
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: n3_wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress_db
      # AQUI: Mudamos a porta para 8080 na configuração do WordPress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080/prova');
        define('WP_SITEURL', 'http://localhost:8080/prova');
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wp_data:/var/www/html

  nginx:
    image: nginx:latest
    container_name: n3_nginx_proxy
    restart: always
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: n3_phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password_123

volumes:
  db_data:
  wp_data: